### ISSUE TITLE
Plugins fail to install in Eclipse Neon due to the lack of org.eclipse.cdt.debug.mi.core

### ISSUE THREAD

**Issue by TommyMurphyTM1234** [RoaLogic/riscv_gnu_eclipse#2]
As identified by Tim Newsome here:

https://groups.google.com/a/groups.riscv.org/d/msg/sw-dev/8dae3T-fS8A/Bd-t5HVUGgAJ

the plugins fail to install in Eclipse Neon 1 (4.6.1) - seemingly because  org.eclipse.cdt.debug.mi.core was removed in that version of Eclipse. The attempt to install fails with this error:

> Cannot complete the install because one or more required items could not be found.
>   Software being installed: RISC-V GNU Toolchain 2016.2.0.201604221055 (com.riscv.cdt.feature.feature.group 2016.2.0.201604221055)
>   Missing requirement: RISC-V GNU Toolchain 2016.2.0.201604221055 (com.riscv.cdt.feature.feature.group 2016.2.0.201604221055) requires 'org.eclipse.cdt.debug.mi.core 0.0.0' but it could not be found

Not sure if/how this can be fixed so that the plugins can be compatible with Neon as well as earlier versions (e.g. Mars, Luna)?

**Comment by TommyMurphyTM1234** [comment]
The latest (at the time of writing) plugin zip (riscv_gnu_plugins_201703300719.zip from here https://github.com/RoaLogic/riscv_gnu_eclipse/tree/master/archive) installs OK in Neon.2 (haven't tried Neon.3 yet) so this issue may have been resolved. I haven't yet played with the plugin in Neon to ensure that it does work but will post/report back when I do...

**Comment by rherveille** [comment]
Cleaning up the dependencies seems to have fixed this.
Closing.
