### ISSUE TITLE
Type on home page :-)

### ISSUE THREAD

**Issue by TommyMurphyTM1234** [RoaLogic/riscv_gnu_eclipse#3]
Very minor issue but I just noticed that there is a typo on the home git page:

https://github.com/RoaLogic/riscv_gnu_eclipse

"Eclipse Pluging for RISC-V GNU Toolchain"

should be

"Eclipse Plugin for RISC-V GNU Toolchain"

:-)

**Comment by rherveille** [comment]
Thanks, fixed.
